/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.proje2;

import java.awt.Color;
import java.awt.Point;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.HashMap;
import java.util.Map;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author zeysu
 */
public class Tavlaa extends javax.swing.JFrame {
private JLabel secilenTas = null;
private int zar1 = 0;
private int zar2 = 0;
private final Map<JLabel, Integer> tasKonumMap = new HashMap<>();
// Tavla tahtası görünümüne göre her pointIndex için sabit x-y pozisyonları
private final int[] pointX = {
    640, 570, 500, 430, 360, 290,   // 0-5  (üst sağdan sola)
    200, 130, 60, -10, -80, -150,   // 6-11 (üst soldan sağa)
    -150, -80, -10, 60, 130, 200,   // 12-17 (alt sol sağa doğru)
    290, 360, 430, 500, 570, 640    // 18-23 (alt sağ sola doğru)
};

private final int[] pointY = {
    30, 30, 30, 30, 30, 30,         // üst sıra
    30, 30, 30, 30, 30, 30,
    400, 400, 400, 400, 400, 400,   // alt sıra
    400, 400, 400, 400, 400, 400
};

    /**
     * Creates new form Tavlaa
     */
    public Tavlaa() {
        initComponents();
         jPanel2.setLayout(null);
    jPanel2.setPreferredSize(new java.awt.Dimension(900, 700)); // paneli büyüt

        baslangicDiziliminiKur(); // taşları yerleştir

       
          jPanel2.revalidate();
    jPanel2.repaint();

        
    }
    
      // Taş seçme ve taşıma işlemi
    private void tasSecildi(JLabel label) {
        if (secilenTas == null) {
            // İlk tıklama → taş seçildi
            secilenTas = label;
            label.setBorder(javax.swing.BorderFactory.createLineBorder(Color.YELLOW, 2));
        } else {
            // İkinci tıklama → hedef seçildi
            if (zar1 == 0) {
                JOptionPane.showMessageDialog(this, "Lütfen önce zar atın!");
                return;
            }

            // seçilen taşı hedef label konumuna taşı
            Point hedefKonum = label.getLocation();
            secilenTas.setLocation(hedefKonum);

            // Temizlik
            secilenTas.setBorder(null);
            secilenTas = null;
            zar1 = 0;
            zarsonucu.setText("Zar: ?");
        }
    }
   private void addPieces(int pointIndex, int count, String color) {
    int x = pointX[pointIndex];
    int yStart = pointY[pointIndex];

    for (int i = 0; i < count; i++) {
        JLabel tas = new JLabel(color.substring(0, 1).toUpperCase());
        tas.setOpaque(true);
        tas.setBackground(color.equals("white") ? Color.LIGHT_GRAY : Color.DARK_GRAY);
        tas.setForeground(Color.BLACK);
        tas.setHorizontalAlignment(JLabel.CENTER);

        int y = (pointIndex < 12) ? yStart + i * 52 : yStart - i * 52;
        tas.setBounds(x, y, 50, 50);
        jPanel2.add(tas);
        tasKonumMap.put(tas, pointIndex);

        tas.addMouseListener(new MouseAdapter() {
            public void mouseClicked(MouseEvent e) {
                tasSecildi(tas);
            }
        });
    }

    jPanel2.repaint();
}

    private void baslangicDiziliminiKur() {
    jPanel2.setLayout(null);

  //  ImageIcon whiteIcon = new ImageIcon(getClass().getResource("/com/mycompany/proje2/icons/white_piece.png"));
    //ImageIcon blackIcon = new ImageIcon(getClass().getResource("/com/mycompany/proje2/icons/black_piece.png"));

    addPieces(0, 2, "white");//icon
    addPieces(11, 5, "white");
    addPieces(16, 3, "white");
    addPieces(18, 5, "white");

    addPieces(5, 5, "black");
    addPieces(7, 3, "black");
    addPieces(12, 5, "black");
    addPieces(23, 2, "black");
}



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        zarsonucu = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 792, Short.MAX_VALUE)
        );

        jButton1.setText("zar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        zarsonucu.setText("jLabel7");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(188, 188, 188)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(zarsonucu, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(700, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addComponent(zarsonucu))
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    zar1 = (int) (Math.random() * 6) + 1;
    zar2 = (int) (Math.random() * 6) + 1;
    zarsonucu.setText("Zar: " + zar1 + " - " + zar2);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tavlaa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tavlaa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tavlaa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tavlaa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tavlaa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel zarsonucu;
    // End of variables declaration//GEN-END:variables
}
