/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.kendininesandn;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.awt.Font;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.Random;
import javax.swing.BorderFactory;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.SwingConstants;

/**
 *
 * @author zeysu
 */
public class ehe extends javax.swing.JFrame {
    private Triangle[] triangles = new Triangle[24];
 private JButton zarAtButton; // Zar atma butonu
    private JLabel zar1Label, zar2Label; // Zarları göstermek için
    private Random random; // Rastgele sayı üreteci
    /**
     * Creates new form ehe
     */
    public ehe() {
          setTitle("Tavla Oyunu");
        setDefaultCloseOperation(EXIT_ON_CLOSE);
        setResizable(false);
        
        // Frame'i büyütelim - genişlik ve yüksekliği artır
        setSize(1100, 700);

        // Ana içerik paneli
        JPanel mainPanel = new JPanel(new BorderLayout());
        
        // Tavla tahtası
        BoardPanel board = new BoardPanel();
        mainPanel.add(board, BorderLayout.CENTER);
        
        // Kontrol paneli (sağ taraf)
        JPanel controlPanel = new JPanel();
        controlPanel.setPreferredSize(new Dimension(100, 600));
        controlPanel.setLayout(new FlowLayout());
        controlPanel.setBackground(new Color(139, 69, 19)); // Ahşap rengi
        
        // Zar atma butonu
        zarAtButton = new JButton("Zar At");
        zarAtButton.setPreferredSize(new Dimension(80, 40));
        zarAtButton.setFocusable(false);
        
        // Zar göstergeleri
        zar1Label = new JLabel("0");
        zar1Label.setPreferredSize(new Dimension(50, 50));
        zar1Label.setHorizontalAlignment(SwingConstants.CENTER);
        zar1Label.setFont(new Font("Arial", Font.BOLD, 24));
        zar1Label.setForeground(Color.WHITE);
        zar1Label.setBackground(new Color(139, 69, 19));
        zar1Label.setOpaque(true);
        zar1Label.setBorder(BorderFactory.createLineBorder(Color.WHITE));
        
        zar2Label = new JLabel("0");
        zar2Label.setPreferredSize(new Dimension(50, 50));
        zar2Label.setHorizontalAlignment(SwingConstants.CENTER);
        zar2Label.setFont(new Font("Arial", Font.BOLD, 24));
        zar2Label.setForeground(Color.WHITE);
        zar2Label.setBackground(new Color(139, 69, 19));
        zar2Label.setOpaque(true);
        zar2Label.setBorder(BorderFactory.createLineBorder(Color.WHITE));
        
        // Random nesnesi oluştur
        random = new Random();
        
        // Zar atma olayı
        zarAtButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                // 1-6 arası rastgele iki zar
                int zar1 = random.nextInt(6) + 1;
                int zar2 = random.nextInt(6) + 1;
                
                // Zarları göster
                zar1Label.setText(String.valueOf(zar1));
                zar2Label.setText(String.valueOf(zar2));
            }
        });
        
        // Kontrol paneline elemanları ekle
        controlPanel.add(zarAtButton);
        controlPanel.add(new JLabel(" ")); // Boşluk
        controlPanel.add(zar1Label);
        controlPanel.add(zar2Label);
        
        // Ana panele kontrol panelini ekle
        mainPanel.add(controlPanel, BorderLayout.EAST);
        
        // Frame'e ana paneli ekle
        setContentPane(mainPanel);
        
        // Merkeze hizala
        setLocationRelativeTo(null);
        setVisible(true);
    }
private void setupTriangles() {
        int width = 60;
        int upY = 0;
        int downY = 600;

        for (int i = 0; i < 12; i++) {
            triangles[i] = new Triangle(i * width + 20, upY, true);
        }
        for (int i = 0; i < 12; i++) {
            triangles[i + 12] = new Triangle((11 - i) * width + 20, downY, false);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2722, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 896, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ehe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ehe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ehe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ehe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ehe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
